name: Deploy Documentation

on:
  push:
    branches:
      - main
    tags: '*'
  pull_request:

jobs:
  deploy_docs:
    name: Deploy Documentation
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1'
      - uses: julia-actions/julia-buildpkg@v1
      - name: Install Documenter package
        run: julia --project=docs -e 'import Pkg; Pkg.add("Documenter")'
      - name: Generate Documentation
        run: |
          julia --project=docs -e '
            using Documenter: DocMeta, doctest
            using tropicalfeynman
            DocMeta.setdocmeta!(tropicalfeynman, :DocTestSetup, :(using tropicalfeynman); recursive=true)
            doctest(tropicalfeynman)'
      - name: Deploy Documentation
        uses: julia-actions/julia-docdeploy@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
