name: Documentation

on:
  push:
    branches:
      - main
    tags: '*'
  pull_request:
  workflow_dispatch:

jobs:
  deploy_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Julia
        uses: julia-actions/setup-julia@latest
        with:
          version: '1'

      - name: Build package
        uses: julia-actions/julia-buildpkg@latest

      - name: Install dependencies and run tests
        run: |
          julia --project=docs -e '
            using Documenter: DocMeta, doctest
            using tropicalfeynman
            DocMeta.setdocmeta!(tropicalfeynman, :DocTestSetup, :(using tropicalfeynman); recursive=true)
            doctest(tropicalfeynman)'
